services:
  - type: web
    name: drone-detection-system
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
